### ISSUE TITLE
[ Feature ] SSL 

### ISSUE THREAD

**Issue by ConnorLacy** [ConnorLacy/passionate-flipflop#4]
### User Story
```
As an engineer
I want to set up SSL certificate management
So that I can provide a secure connection to my website
```

### Acceptance Criteria: 
- [x] Certbot utility manages SSL expiring certificates
- [x] Certificate challenges pass for `connorlacy.com` and `www.connorlacy.com`
- [x] Website displays SSL secure connection identifier

### Tasks:
- [x] Acquire server instance from GCP, Digital Ocean, or Home Server
- [x] Identify certificate management authority
- [x] Implement certificate management authority
- [x] Configure Nginx to comply with certificate management authority

**Comment by ConnorLacy** [comment]
## Helpful for later
[Here's a how-to on setting up SSL on the digitalocean server](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04)

**Comment by ConnorLacy** [comment]
Hitting a roadblock waiting for DNS servers to update on DigitalOcean side. Try running this command again in a few hours: sudo certbot --nginx -d connorlacy.com -d www.connorlacy.com

**Comment by ConnorLacy** [comment]
## Resolved!

![image](https://user-images.githubusercontent.com/43463172/93686825-fc14ba80-fa86-11ea-888a-6f260b07ec54.png)

> Note: The problem holding me back was only having `www.connorlacy.com` registered as a domain for my server on the DigitalOcean control panel. By adding `connorlacy.com` and creating an 'A' record in the DNS records, the certificates were successfully generated.
