### ISSUE TITLE
[ Feature ] Server setup

### ISSUE THREAD

**Issue by ConnorLacy** [ConnorLacy/passionate-flipflop#7]
### User Story
```
As an engineer
I want to set up a service-provided server
So that I can host my personal website
```

### Acceptance Criteria: 
- [x] Application starts on server boot
- [x] Application managed by process manager (pm2)
- [x] Server provides utility for SSL certificate mangement (certbot)
- [x] Domain name is connected to server app instance

### Tasks:
- [x] Acquire server instance from GCP, Digital Ocean, or Home Server
- [x] Connect server to domain name
- [x] Create example app
- [x] Host app on server

**Comment by ConnorLacy** [comment]
# Notes
- [Nginx Setup & Configuration Guide](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04#step-5-setting-up-server-blocks-(recommended))

**Comment by ConnorLacy** [comment]
Hitting a roadblock waiting for DNS servers to update on DigitalOcean side. Try running this command again in a few hours: `sudo certbot --nginx -d connorlacy.com -d www.connorlacy.com`
